# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node Robot Remote Server CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        robot-version: [2.8.7, 2.9.2, 3.0.4]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} and 
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        robot-version: ${{ matrix.robot-version }}
    - run: |
        sudo pip install robotframework==${{ matrix.robot-version }}
        npm install
        npm test
